version: '3.8'
services:
    php-apache:
        container_name: idor-invalid-if-statement-26
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1337:80
